/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Asset } from '../model/Asset';
import { HttpFile } from '../http/http';

export class AssetsResponse {
    /**
    * Number of assets to return per page
    */
    'items': Array<Asset>;
    /**
    * Number of total items
    */
    'total': number;
    /**
    * Number of items to return per page
    */
    'limit': number;
    /**
    * Page number
    */
    'page': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Asset>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

