/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Collection {
    /**
    * The unique identifier for the collection entity.
    */
    'id': string;
    /**
    * The unique identifier that can be provided by game studio.
    */
    'uniqueId': string;
    /**
    * The name of the collection.
    */
    'name': string;
    /**
    * A brief description of the collection.
    */
    'description': string;
    /**
    * An image representing the collection's logo.
    */
    'logoImage': string;
    /**
    * Additional images associated with the collection, such as screenshots or promotional images.
    */
    'medias': Array<string>;
    /**
    * The main or featured image associated with the game. You can set it from the dashboard as main image.
    */
    'mainMedia': string;
    /**
    * A unique URL for the collection on the L3vels platform.
    */
    'url': string;
    /**
    * A URL link to the collection's webpage.
    */
    'webLink': string;
    /**
    * The supply represents the number of assets that are available within the Collection.
    */
    'supply': number;
    /**
    * Custom properties that are unique to the collection and defined by the developer to categorize and filter them.
    */
    'customPropertyProps': any;
    /**
    * Additional social links associated with the collection
    */
    'socialLinks': Array<string>;
    /**
    * Custom assets fields associated with the collection.
    */
    'customAssetProps': any;
    /**
    * The category or categories that the collection belongs to.
    */
    'categories': any;
    /**
    * The current status of the collection. Possible values are: Draft, Active
    */
    'status': string;
    /**
    * The unique identifier of the account that the Collection belongs to.
    */
    'accountId': string;
    /**
    * The unique identifier of the game that the collection is associated with. This allows developers to organize their collections by game and helps with tracking and reporting.
    */
    'gameId': string;
    /**
    * The date when the collection was created.
    */
    'createdOn': Date;
    /**
    * The date when the collection was last modified.
    */
    'modifiedOn': Date;
    /**
    * The Id of the user who created the collection.
    */
    'createdBy': string;
    /**
    * The Id of the user who last modified the collection.
    */
    'modifiedBy': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "uniqueId",
            "baseName": "unique_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "logoImage",
            "baseName": "logo_image",
            "type": "string",
            "format": ""
        },
        {
            "name": "medias",
            "baseName": "medias",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainMedia",
            "baseName": "main_media",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "webLink",
            "baseName": "web_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "supply",
            "baseName": "supply",
            "type": "number",
            "format": ""
        },
        {
            "name": "customPropertyProps",
            "baseName": "custom_property_props",
            "type": "any",
            "format": ""
        },
        {
            "name": "socialLinks",
            "baseName": "social_links",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "customAssetProps",
            "baseName": "custom_asset_props",
            "type": "any",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "any",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "gameId",
            "baseName": "game_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdOn",
            "baseName": "created_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modifiedOn",
            "baseName": "modified_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifiedBy",
            "baseName": "modified_by",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Collection.attributeTypeMap;
    }

    public constructor() {
    }
}

