/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Game {
    /**
    * The unique identifier for the Game entity.
    */
    'id': string;
    /**
    * The name of the Game.
    */
    'name': string;
    /**
    * A brief description of the Game.
    */
    'description': string;
    /**
    * The category or genre of the Game.
    */
    'category': string;
    /**
    * The logo or icon associated with the Game.
    */
    'logoImage': string;
    /**
    * Additional images associated with the collection, such as screenshots or promotional images.
    */
    'medias': Array<string>;
    /**
    * Additional social links associated with the collection
    */
    'socialLinks': Array<string>;
    /**
    * The main or featured image associated with the Game. You can set it from the Dashboard as main image.
    */
    'mainMedia': string;
    /**
    * A unique URL for the game on the L3vels platform.
    */
    'url': string;
    /**
    * The URL for the Game's website or landing page.
    */
    'webLink': string;
    /**
    * The link to the Game's Discord server.
    */
    'discord': string;
    /**
    * The link to the Game's official Twitter account.
    */
    'twitter': string;
    /**
    * The link to the Game's official Instagram account.
    */
    'instagram': string;
    /**
    *  A phone number for contacting the Game's developers or support team.
    */
    'contactPhone': string;
    /**
    * An email address for contacting the Game's developers or support team.
    */
    'contactEmail': string;
    /**
    * The current status of the Game, such as \"Draft\", \"Active\", or \"Inactive\".
    */
    'status': string;
    /**
    *  The unique identifier of the account that the Game belongs to. This allows developers to manage multiple Games across multiple accounts.
    */
    'accountId': string;
    /**
    * The date and time that the Game entity was created.
    */
    'createdOn': Date;
    /**
    * The date and time that the Game entity was last modified.
    */
    'modifiedOn': Date;
    /**
    * The user or system that created the Game entity.
    */
    'createdBy': string;
    /**
    * The user or system that last modified the Game entity.
    */
    'modifiedBy': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "logoImage",
            "baseName": "logo_image",
            "type": "string",
            "format": ""
        },
        {
            "name": "medias",
            "baseName": "medias",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "socialLinks",
            "baseName": "social_links",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainMedia",
            "baseName": "main_media",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "webLink",
            "baseName": "web_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "discord",
            "baseName": "discord",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactPhone",
            "baseName": "contact_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactEmail",
            "baseName": "contact_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdOn",
            "baseName": "created_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modifiedOn",
            "baseName": "modified_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifiedBy",
            "baseName": "modified_by",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Game.attributeTypeMap;
    }

    public constructor() {
    }
}

