/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MintBatchInput {
    /**
    * Game Id
    */
    'gameId': string;
    /**
    * Collection Id
    */
    'collectionId': string;
    /**
    * Player address to mint token to
    */
    'playerAddress': string;
    /**
    * Player ID to mint to. You can provide this or player_address
    */
    'playerId': string;
    /**
    * Array of tokens to mint
    */
    'assets': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameId",
            "baseName": "game_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerAddress",
            "baseName": "player_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerId",
            "baseName": "player_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MintBatchInput.attributeTypeMap;
    }

    public constructor() {
    }
}

