/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Player {
    /**
    * The unique identifier for the Player entity.
    */
    'id': string;
    /**
    * The unique ID of the Player that can be provided by customers or generated by us.
    */
    'uniqueId': string;
    /**
    * The name of the player
    */
    'name': string;
    /**
    * Username of the player
    */
    'username': string;
    /**
    * Email of the player
    */
    'email': string;
    /**
    * Avatar URL of the player
    */
    'avatar': string;
    /**
    * Custom props for player
    */
    'customProps': any;
    /**
    * The date when player was active last time
    */
    'lastSeen': Date;
    /**
    * The unique identifier of the account that the Player belongs to.
    */
    'accountId': string;
    /**
    * The unique identifier of the game that the Player is associated with. This allows developers to organize their players by game and helps with tracking and reporting. Example: Player Jack is associated with game Fortnite.
    */
    'gameId': string;
    /**
    * The date when the player was created.
    */
    'createdOn': Date;
    /**
    * The date when the player was last modified.
    */
    'modifiedOn': Date;
    /**
    * The Id of the user who created the player.
    */
    'createdBy': string;
    /**
    * The Id of the user who last modified the player.
    */
    'modifiedBy': string;
    /**
    * Boolean value indicating whether the player has wallet or not
    */
    'isCreateWallet': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "uniqueId",
            "baseName": "unique_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "customProps",
            "baseName": "custom_props",
            "type": "any",
            "format": ""
        },
        {
            "name": "lastSeen",
            "baseName": "last_seen",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "gameId",
            "baseName": "game_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdOn",
            "baseName": "created_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modifiedOn",
            "baseName": "modified_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifiedBy",
            "baseName": "modified_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCreateWallet",
            "baseName": "is_create_wallet",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Player.attributeTypeMap;
    }

    public constructor() {
    }
}

