/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SetContractUriInput {
    /**
    * Game Id
    */
    'gameId': string;
    /**
    * Collection Id
    */
    'collectionId': string;
    /**
    * Contract URI
    */
    'contractUri': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameId",
            "baseName": "game_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractUri",
            "baseName": "contract_uri",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SetContractUriInput.attributeTypeMap;
    }

    public constructor() {
    }
}

