/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateAssetInput {
    /**
    * The name of the asset.
    */
    'name'?: string;
    /**
    * The story of asset.
    */
    'description'?: string;
    /**
    * Price of asset
    */
    'price'?: number;
    /**
    * Supply of asset
    */
    'supply'?: number;
    /**
    * Asset URL
    */
    'assetUrl'?: string;
    /**
    * Custom props for asset.
    */
    'customProps'?: any;
    /**
    * Collection ID to find and update the asset in. Example: Update AK-47 asset in Weapons collection.
    */
    'collectionId': string;
    /**
    * Game ID to update the asset in. Example: Call of Duty
    */
    'gameId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "supply",
            "baseName": "supply",
            "type": "number",
            "format": ""
        },
        {
            "name": "assetUrl",
            "baseName": "asset_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "customProps",
            "baseName": "custom_props",
            "type": "any",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "gameId",
            "baseName": "game_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateAssetInput.attributeTypeMap;
    }

    public constructor() {
    }
}

