/* tslint:disable */
/* eslint-disable */
/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.1
 * Contact: games@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Transaction,
} from '../models';
import {
    TransactionFromJSON,
    TransactionToJSON,
} from '../models';

export interface TransactionControllerTransactionByIdRequest {
    authorization: string;
    id: string;
    projectId: string;
}

export interface TransactionControllerTransactionsRequest {
    authorization: string;
    projectId: string;
    collectionId?: string;
    playerId?: string;
    sort?: string;
    order?: TransactionControllerTransactionsOrderEnum;
    searchText?: string;
    limit?: number;
    page?: number;
}

export interface TransactionControllerWebhookRequest {
    authorization: string;
}

/**
 * 
 */
export class TransactionApi extends runtime.BaseAPI {

    /**
     * Retrieve transaction by ID
     * Retrieve Transaction by ID
     */
    async transactionControllerTransactionByIdRaw(requestParameters: TransactionControllerTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transaction>> {
        if (requestParameters.authorization === null || requestParameters.authorization === undefined) {
            throw new runtime.RequiredError('authorization','Required parameter requestParameters.authorization was null or undefined when calling transactionControllerTransactionById.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling transactionControllerTransactionById.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling transactionControllerTransactionById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['Authorization'] = String(requestParameters.authorization);
        }

        const response = await this.request({
            path: `/v1/transaction/{project_id}/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
    }

    /**
     * Retrieve transaction by ID
     * Retrieve Transaction by ID
     */
    async transactionControllerTransactionById(requestParameters: TransactionControllerTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
        const response = await this.transactionControllerTransactionByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all transactions.
     * Retrieve transactions
     */
    async transactionControllerTransactionsRaw(requestParameters: TransactionControllerTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transaction>> {
        if (requestParameters.authorization === null || requestParameters.authorization === undefined) {
            throw new runtime.RequiredError('authorization','Required parameter requestParameters.authorization was null or undefined when calling transactionControllerTransactions.');
        }

        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling transactionControllerTransactions.');
        }

        const queryParameters: any = {};

        if (requestParameters.projectId !== undefined) {
            queryParameters['project_id'] = requestParameters.projectId;
        }

        if (requestParameters.collectionId !== undefined) {
            queryParameters['collection_id'] = requestParameters.collectionId;
        }

        if (requestParameters.playerId !== undefined) {
            queryParameters['player_id'] = requestParameters.playerId;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.order !== undefined) {
            queryParameters['order'] = requestParameters.order;
        }

        if (requestParameters.searchText !== undefined) {
            queryParameters['search_text'] = requestParameters.searchText;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['Authorization'] = String(requestParameters.authorization);
        }

        const response = await this.request({
            path: `/v1/transaction`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
    }

    /**
     * Retrieve all transactions.
     * Retrieve transactions
     */
    async transactionControllerTransactions(requestParameters: TransactionControllerTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
        const response = await this.transactionControllerTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async transactionControllerWebhookRaw(requestParameters: TransactionControllerWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authorization === null || requestParameters.authorization === undefined) {
            throw new runtime.RequiredError('authorization','Required parameter requestParameters.authorization was null or undefined when calling transactionControllerWebhook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['Authorization'] = String(requestParameters.authorization);
        }

        const response = await this.request({
            path: `/v1/transaction/webhook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async transactionControllerWebhook(requestParameters: TransactionControllerWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transactionControllerWebhookRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const TransactionControllerTransactionsOrderEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
} as const;
export type TransactionControllerTransactionsOrderEnum = typeof TransactionControllerTransactionsOrderEnum[keyof typeof TransactionControllerTransactionsOrderEnum];
