/* tslint:disable */
/* eslint-disable */
/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.1
 * Contact: games@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAssetDto
 */
export interface UpdateAssetDto {
    /**
     * The name of the asset.
     * @type {string}
     * @memberof UpdateAssetDto
     */
    name?: string;
    /**
     * The story of asset.
     * @type {string}
     * @memberof UpdateAssetDto
     */
    description?: string;
    /**
     * Price of asset
     * @type {number}
     * @memberof UpdateAssetDto
     */
    price?: number;
    /**
     * Supply of asset
     * @type {number}
     * @memberof UpdateAssetDto
     */
    supply?: number;
    /**
     * Asset URL
     * @type {string}
     * @memberof UpdateAssetDto
     */
    assetUrl?: string;
    /**
     * Custom props for asset.
     * @type {object}
     * @memberof UpdateAssetDto
     */
    customProps?: object;
    /**
     * Collection ID to find and update the asset in. Example: Update AK-47 asset in Weapons collection.
     * @type {string}
     * @memberof UpdateAssetDto
     */
    collectionId: string;
    /**
     * Game/project ID to update the asset in. Example: Call of Duty
     * @type {string}
     * @memberof UpdateAssetDto
     */
    projectId: string;
}

/**
 * Check if a given object implements the UpdateAssetDto interface.
 */
export function instanceOfUpdateAssetDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "collectionId" in value;
    isInstance = isInstance && "projectId" in value;

    return isInstance;
}

export function UpdateAssetDtoFromJSON(json: any): UpdateAssetDto {
    return UpdateAssetDtoFromJSONTyped(json, false);
}

export function UpdateAssetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAssetDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'supply': !exists(json, 'supply') ? undefined : json['supply'],
        'assetUrl': !exists(json, 'asset_url') ? undefined : json['asset_url'],
        'customProps': !exists(json, 'custom_props') ? undefined : json['custom_props'],
        'collectionId': json['collection_id'],
        'projectId': json['project_id'],
    };
}

export function UpdateAssetDtoToJSON(value?: UpdateAssetDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'supply': value.supply,
        'asset_url': value.assetUrl,
        'custom_props': value.customProps,
        'collection_id': value.collectionId,
        'project_id': value.projectId,
    };
}

