/* tslint:disable */
/* eslint-disable */
/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetContractUriInput
 */
export interface SetContractUriInput {
    /**
     * Game Id
     * @type {string}
     * @memberof SetContractUriInput
     */
    gameId: string;
    /**
     * Collection Id
     * @type {string}
     * @memberof SetContractUriInput
     */
    collectionId: string;
    /**
     * Contract URI
     * @type {string}
     * @memberof SetContractUriInput
     */
    contractUri: string;
}

/**
 * Check if a given object implements the SetContractUriInput interface.
 */
export function instanceOfSetContractUriInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gameId" in value;
    isInstance = isInstance && "collectionId" in value;
    isInstance = isInstance && "contractUri" in value;

    return isInstance;
}

export function SetContractUriInputFromJSON(json: any): SetContractUriInput {
    return SetContractUriInputFromJSONTyped(json, false);
}

export function SetContractUriInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetContractUriInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameId': json['game_id'],
        'collectionId': json['collection_id'],
        'contractUri': json['contract_uri'],
    };
}

export function SetContractUriInputToJSON(value?: SetContractUriInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'game_id': value.gameId,
        'collection_id': value.collectionId,
        'contract_uri': value.contractUri,
    };
}

