/* tslint:disable */
/* eslint-disable */
/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetSaleStatusDto
 */
export interface SetSaleStatusDto {
    /**
     * Project Id
     * @type {string}
     * @memberof SetSaleStatusDto
     */
    projectId: string;
    /**
     * Collection Id
     * @type {string}
     * @memberof SetSaleStatusDto
     */
    collectionId: string;
    /**
     * Sale Status of the contract
     * @type {object}
     * @memberof SetSaleStatusDto
     */
    saleStatus: object;
}

/**
 * Check if a given object implements the SetSaleStatusDto interface.
 */
export function instanceOfSetSaleStatusDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "collectionId" in value;
    isInstance = isInstance && "saleStatus" in value;

    return isInstance;
}

export function SetSaleStatusDtoFromJSON(json: any): SetSaleStatusDto {
    return SetSaleStatusDtoFromJSONTyped(json, false);
}

export function SetSaleStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetSaleStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'collectionId': json['collection_id'],
        'saleStatus': json['sale_status'],
    };
}

export function SetSaleStatusDtoToJSON(value?: SetSaleStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'project_id': value.projectId,
        'collection_id': value.collectionId,
        'sale_status': value.saleStatus,
    };
}

